package com.example.myapplication

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle


class MainActivity : AppCompatActivity() {
SKSJDKSJSKSJLSDJLJSLKDJSLKDJSA
    SLJASLJSLJDSLDJSLÑJSDÑALSDJSLÑD
    SLSDALSDJSLDSALKSDLKDSÑLDKÑ
    SJDASLKSLSKÑSDKS
    KLKJLÑDJDLKASJDLSDJSLDJSDHOOISDFOIWQFWEIOFEOIWEIFHEWIFHEOFJWEFIWEF
    SLKJSLKSDÑSJASÑLDJSDÑLSJDASÑDJEEJFE
    LÑLSÑJDASÑLDJAS

}